TeamBasicRiki/Riki/wiki/web/routes.py
"""
    Routes
    ~~~~~~
"""
import base64
from io import BytesIO
from flask import Blueprint, make_response, send_file
from wiki.web.user import UserManager
from flask import flash
from flask import redirect
from flask import render_template
from flask import url_for
from flask import request, jsonify
from flask_login import current_user
from flask_login import login_required
from flask_login import login_user
from flask_login import logout_user
from wiki.core import Processor
from wiki.web.converter import Converter, get_file_size
from wiki.web.forms import EditorForm
from wiki.web.forms import LoginForm
from wiki.web.forms import SearchForm
from wiki.web.forms import URLForm
from wiki.web import current_wiki
from wiki.web import current_users
from wiki.web.user import protect
from wiki.web.forms import RegisterForm
from config import USER_DIR
from wiki.web.user import UserRegistrationController
from wiki.web.file_storage import FileManager

bp = Blueprint('wiki', __name__)
DIRECTORY = "UserFileStorage"


@bp.route('/')
@protect
def home():
    page = current_wiki.get('home')
    if page:
        return display('home')
    return render_template('home.html')


@bp.route('/index/')
@protect
def index():
    pages = current_wiki.index()
    return render_template('index.html', pages=pages)


@bp.route('/<path:url>/')
@protect
def display(url):
    page = current_wiki.get_or_404(url)
    return render_template('page.html', page=page)


@bp.route('/create/', methods=['GET', 'POST'])
@protect
def create():
    form = URLForm()
    if form.validate_on_submit():
        return redirect(url_for(
            'wiki.edit', url=form.clean_url(form.url.data)))
    return render_template('create.html', form=form)


@bp.route('/edit/<path:url>/', methods=['GET', 'POST'])
@protect
def edit(url):
    page = current_wiki.get(url)
    form = EditorForm(obj=page)
    if form.validate_on_submit():
        if not page:
            page = current_wiki.get_bare(url)
        form.populate_obj(page)
        page.save()
        flash('"%s" was saved.' % page.title, 'success')
        return redirect(url_for('wiki.display', url=url))
    return render_template('editor.html', form=form, page=page)


@bp.route('/preview/', methods=['POST'])
@protect
def preview():
    data = {}
    processor = Processor(request.form['body'])
    data['html'], data['body'], data['meta'] = processor.process()
    return data['html']


@bp.route('/move/<path:url>/', methods=['GET', 'POST'])
@protect
def move(url):
    page = current_wiki.get_or_404(url)
    form = URLForm(obj=page)
    if form.validate_on_submit():
        newurl = form.url.data
        current_wiki.move(url, newurl)
        return redirect(url_for('wiki.display', url=newurl))
    return render_template('move.html', form=form, page=page)


@bp.route('/download/<path:url>/', methods=['GET'])
@protect
def download(url):
    """
    Route to download a wiki page in different file formats.

    Args:
        url (str): The URL path of the wiki page.

    Returns:
        flask.Response: The response containing the requested file.

    """
    page = current_wiki.get_or_404(url)
    filetype = request.args.get('fileType', 'txt')

    if filetype.lower() == 'md':
        # If the requested file type is md, directly send the markdown content
        return send_file(
            BytesIO(page.content.encode('utf-8')),
            as_attachment=True,
            download_name=f'{url}.{filetype}',
            mimetype='text/markdown'
        )
    else:
        converter = Converter(page)
        conversion_method = getattr(converter, f'convert_to_{filetype.upper()}')
        file_content, _ = conversion_method()

        # Convert base64 to bytes
        file_bytes = base64.b64decode(file_content)

        return send_file(
            BytesIO(file_bytes),
            as_attachment=True,
            download_name=f'{url}.{filetype}',
            mimetype='application/octet-stream'
        )


@bp.route('/convert/<path:url>/', methods=['POST'])
@protect
def convert(url):
    """
    Route to convert a wiki page to different file formats.

    Args:
        url (str): The URL path of the wiki page.

    Returns:
        flask.Response: The response containing the converted file.

    """
    data = request.json
    filetype = data.get('fileType')

    if filetype is None:
        return jsonify({'error': 'Invalid request. Missing fileType parameter.'}), 400

    page = current_wiki.get_or_404(url)

    try:
        if filetype.lower() == 'md':
            file_size_info = {
                'fileType': filetype,
                'fileSize': get_file_size(page.content),
                'conversionStatus': 'Success',
            }
            response_data = {'result': file_size_info}
        else:
            converter = Converter(page)
            conversion_method = getattr(converter, f'convert_to_{filetype.upper()}')
            file_content, file_size = conversion_method()

            response = make_response(file_content)
            response.headers['Content-Disposition'] = f'attachment; filename={url}.{filetype}'
            response.headers['Content-Type'] = 'application/octet-stream'
            response.headers['Content-Length'] = str(len(file_content))

            file_size_info = {
                'fileType': filetype,
                'fileSize': file_size,
                'conversionStatus': 'Success',
            }

            response_data = {'result': file_size_info}
    except Exception as e:
        # If an exception occurs during conversion, set conversionStatus to 'Failed'
        file_size_info = {
            'fileType': filetype,
            'fileSize': None,
            'conversionStatus': 'Failed',
            'error': str(e),
        }
        response_data = {'result': file_size_info}

    return jsonify(response_data)


@bp.route('/delete/<path:url>/')
@protect
def delete(url):
    page = current_wiki.get_or_404(url)
    current_wiki.delete(url)
    flash('Page "%s" was deleted.' % page.title, 'success')
    return redirect(url_for('wiki.home'))


@bp.route('/tags/')
@protect
def tags():
    tags = current_wiki.get_tags()
    return render_template('tags.html', tags=tags)


@bp.route('/tag/<string:name>/')
@protect
def tag(name):
    tagged = current_wiki.index_by_tag(name)
    return render_template('tag.html', pages=tagged, tag=name)


@bp.route('/search/', methods=['GET', 'POST'])
@protect
def search():
    form = SearchForm()
    if form.validate_on_submit():
        results = current_wiki.search(form.term.data, form.ignore_case.data)
        return render_template('search.html', form=form,
                               results=results, search=form.term.data)
    return render_template('search.html', form=form, search=None)


@bp.route('/user/login/', methods=['GET', 'POST'])
def user_login():
    """
    Handles user login.

    Displays the login form and processes the form submission.
    """
    form = LoginForm()
    if form.validate_on_submit():
        user = current_users.get_user(form.name.data)
        login_user(user)
        user.set('authenticated', True)
        flash('Login successful.', 'success')
        return redirect(request.args.get("next") or url_for('wiki.index'))
    return render_template('login.html', form=form)


@bp.route('/user/logout/')
@login_required
def user_logout():
    """
    Handles user logout.

    Logs out the current user and sets 'authenticated' to False.
    """
    current_user.set('authenticated', False)
    logout_user()
    flash('Logout successful.', 'success')
    return redirect(url_for('wiki.index'))


@bp.route('/user/')
@login_required
def user_index():
    """
    Displays user account information.

    Retrieves and displays information about the currently logged-in user.
    """
    user_data = {
        'name': current_user.name,
        'email': current_user.get('email'),
        'active': current_user.is_active(),
        'authenticated': current_user.is_authenticated(),
        'roles': current_user.get('roles'),
    }
    return render_template('account.html', user=user_data)


@bp.route('/user/edit')
def user_edit():
    pass


@bp.route('/user/create/', methods=['GET', 'POST'])
def user_create():
    """
    Handles user registration.

    Displays the registration form and processes the form submission.
    """
    form = RegisterForm()
    user_manager = UserManager(USER_DIR)
    registration_controller = UserRegistrationController(user_manager)

    if form.validate_on_submit() and registration_controller.form_field_validation(form):
        return redirect(url_for('wiki.user_login'))

    return render_template('register.html', form=form)


@bp.route('/user/<int:user_id>/')
def user_admin(user_id):
    pass


@bp.route('/user/delete/<string:user_id>/', methods=['GET', 'POST'])
@protect
def user_delete(user_id):
    """
    Handles user deletion.

    Displays the confirmation form for user deletion and processes the deletion if confirmed.
    """
    user = current_users.get_user(user_id)
    if request.method == 'POST':
        user_manager = UserManager(USER_DIR)
        user_manager.delete_user(user.name)
        flash('User {} has been deleted.'.format(user.name), 'success')
        return redirect(url_for('wiki.index'))

    return render_template('delete_user.html', user=user)


"""
    Error Handlers
    ~~~~~~~~~~~~~~
"""


@bp.errorhandler(404)
def page_not_found(error):
    return render_template('404.html'), 404


@bp.route('/file_storage/', methods=['GET', 'POST'])
@protect
def file_storage():
    file_manager = FileManager(DIRECTORY)
    files = file_manager.get_downloadable_files()
    return render_template('file_storage.html', files=files)


@bp.route('/delete_file/<path:file_name>/')
@protect
def delete_file(file_name):
    file_manager = FileManager(DIRECTORY)
    success = file_manager.delete_file(file_name)
    if success:
        flash(f"Successfully deleted file {file_name}")

TeamBasicRiki/Riki/wiki/web/templates/account.html
{% extends "base.html" %}

{% block title -%}
    Account Profile
{%- endblock title %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <h2>{{ user.name }}'s Profile</h2>
                <ul class="list-group">
                    <li class="list-group-item">
                        <strong>Email:</strong> {{ user.email }}
                    </li>
                    <li class="list-group-item">
                        <strong>Active:</strong> {% if user.active %}Yes{% else %}No{% endif %}
                    </li>
                    <li class="list-group-item">
                        <strong>Authenticated:</strong> {% if user.authenticated %}Yes{% else %}No{% endif %}
                    </li>
                    <li class="list-group-item">
                        <strong>Roles:</strong> {{ user.roles | join(', ') }}
                    </li>

                </ul>
                {#                <a class="btn btn-primary mt-3" href="{{ url_for('wiki.user_edit') }}">Edit Profile</a>#}
               <a class="btn btn-danger mt-3" href="{{ url_for('wiki.user_delete', user_id=current_user.get_id()) }}">Delete Profile</a>

            </div>
        </div>
    </div>
{% endblock content %}

TeamBasicRiki/Riki/wiki/web/templates/create.html
{% extends "base.html" %}

{% block title %}Create a new page{% endblock title %}
{% block content %}
<form method="POST" class="form-inline">
	{{ form.hidden_tag() }}
	{{ input(form.url, placeholder="URL of the new page", autocomplete="off") }}
	<input type="submit" class="btn btn-success" value="Create">
</form>
{% endblock content %}

{% block sidebar %}
<p class="alert alert-success">Thank you for creating new content!</p>
{% endblock sidebar %}

TeamBasicRiki/Riki/wiki/web/templates/delete_user.html
{% extends "base.html" %}

{% block title -%}
    Delete User '{{ user.name }}'
{%- endblock title %}

{% block content %}
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card mt-5">
                <div class="card-header">
                    <h2 class="text-center">Delete User '{{ user.name }}'</h2>
                </div>
                <div class="card-body">
                    <p class="text-center">Are you sure you want to delete the user '{{ user.name }}'?</p>

                    <form method="post" action="{{ url_for('wiki.user_delete', user_id=user.name) }}" class="text-center">
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>

                    <a href="{{ url_for('wiki.user_index') }}" class="btn btn-secondary mt-2">Cancel</a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

TeamBasicRiki/Riki/wiki/web/templates/editor.html
{% extends "base.html" %}

{% block title -%}
Wiki Editor
{%- endblock title %}

{% block content %}
<ul class="nav nav-tabs">
	<li class="active"><a href="#editor" data-toggle="tab">Editor</a></li>
	<li><a href="#preview" data-toggle="tab" id="previewlink">Preview</a></li>
</ul>
<div class="tab-content">
	<div class="tab-pane active" id="editor">
		<form method="post" class="form">
			{{ form.hidden_tag() }}
			{{ input(form.title, placeholder="Title", class="span7", autocomplete="off") }}
			{{ input(form.body, placeholder="Markdown", class="span7", rows="20") }}
			{{ input(form.tags, placeholder="Tags (comma separated)", class="span7", autocomplete="off") }}
			<div class="form-actions">
        <div class="pull-left">
          <a class="btn" href="#preview" id="previewbtn">Preview</a>
        </div>
				<div class="pull-right">
          <a class="btn" href="{{ url_for('wiki.display', url=page.url) }}">Cancel</a>
					<button class="btn btn-success" type="submit">Save</button>
				</div>
			</div>
		</form>
	</div>
	<div class="tab-pane" id="preview"></div>
</div>
{% endblock content %}

{% block sidebar %}
<h3>Editor How-To</h3>
<p>This editor is <a href="http://daringfireball.net/projects/markdown/">markdown</a> featured.</p>
<pre><code>* I
* am
* a
* list</code></pre>
Turns into:
<ul>
<li>I</li>
<li>am</li>
<li>a</li>
<li>list</li>
</ul>
<p><code>**bold** and *italics*</code> turn into <strong>bold</strong> and <em>italics</em>. Very easy!</p>
<p>Create links with <code>[NoTube](http://www.notube.com)</code>. They turn into <a href="http://www.notube.com">NoTube</a>.</p>
<p>Headers are as follows:</p>
<pre><code># Level 1
## Level 2
### Level 3</code></pre>
<p></p>

{% endblock sidebar %}

{% block postscripts -%}
{{ super() }}
$('#previewlink').on('click', function() {
	var $form = $('.form');
  var $inputs = $form.find('input, textarea, button');
  var $pre = $('#preview');
  var bodycontent = 'title: preview\n\n' + $form.find('textarea').val();
  $inputs.prop('disabled', true);
  $pre.removeClass('alert').removeClass('alert-error').html("Loading...");
  $.ajax({
    url: "{{ url_for('wiki.preview') }}",
    type: "POST",
    data: { body: bodycontent },
    success: function(msg) {
      $pre.html(msg);
      console.log(msg);
    },
    error: function() {
			$pre.addClass('alert').addClass('alert-error');
      $pre.html('There was a problem with the preview.');
    },
    complete: function() {
      $inputs.prop('disabled', false);
    }
  });
});
$('#previewbtn').on('click', function(event) {
	event.preventDefault();
	$('#previewlink').click();
});
{%- endblock postscripts %}

TeamBasicRiki/Riki/wiki/web/templates/file_storage.html
{% extends "base.html" %}

{% block title -%}File Storage{%- endblock title %}
{% block content %}
    <form action={{ url_for("wiki.upload_file") }} method="post" enctype="multipart/form-data">
        <label for="file" class="label label-inverse" style="font-size: 16px">Upload File</label>
        <input type="file" name="file" class="btn btn-info"/>
        <input type="submit" class="btn btn-success" value="Upload">
    </form>
    <h2 class="page-header">Downloadable Files</h2>
    <table class="table table-striped">
        <tr>
            <th>File Name</th>
            <th>Download</th>
            <th>Delete</th>
        </tr>
        {% for file in files %}
            <tr>
                <td>{{ file }}</td>
                <td><a href="{{ url_for('wiki.download_file', file_name=file) }}" class="btn">Download</a></td>
                <td><a href="{{ url_for('wiki.delete_file', file_name=file) }}" class="btn btn-danger">Delete</a></td>
            </tr>
        {% endfor %}
    </table>
{% endblock content %}

TeamBasicRiki/Riki/wiki/web/templates/helpers.html
{% macro input(field) -%}
	<div class="control-group {% if field.errors %}error{% endif %}">
		{% if field.type == 'BooleanField' %}
			<div class="controls">
				<label for="{{ field.name }}" class="checkbox">
					{{ field(**kwargs) }}
					{{ field.label.text }}
				</label>
			</div>
		{% else %}
			<label for="{{ field.name }}" class="control-label">{{ field.label.text }}</label>
			<div class="controls">
				{{ field(**kwargs) }}
				{% if field.errors %}
					<div>
						{% for error in field.errors %}
							<span class="help-inline">
								{{ error }}
							</span>
						{% endfor %}
					</div>
				{% endif %}
			</div>
		{% endif %}
	</div>
{%- endmacro %}

TeamBasicRiki/Riki/wiki/web/templates/home.html
{% extends "base.html" %}
{% block title -%}
	Welcome to your new wiki!
{% endblock title %}

{% block content %}
<p>You did not create any content yet. Your wiki recommends you, to do so now, as every user will see this page first, and you would want to make a good impression, wouldn't you?</p>
<p><a href="{{ url_for('wiki.edit', url='home') }}" class="btn btn-success">Create a homepage</a></p>
{% endblock %}

TeamBasicRiki/Riki/wiki/web/templates/index.html
{% extends "base.html" %}

{% block title %}Page Index{% endblock title %}

{% block content %}
{% if pages %}
	<table class="table">
		<thead>
			<tr>
				<th>Title</th>
				<th>URL</th>
			</tr>
		</thead>
		<tbody>
			{% for page in pages %}
				<tr>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.title }}</a></td>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.url }}</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>There are no pages yet.</p>
{% endif %}
{% endblock content %}

{% block sidebar %}
<ul class="nav nav-tabs nav-stacked">
	<li><a href="{{ url_for('wiki.create') }}">New Page</a></li>
	<li><a href="{{ url_for('wiki.tags') }}">Tag List</a></li>
	<li><a href="{{ url_for('wiki.search') }}">Search</a></li>
</ul>
{% endblock sidebar %}

TeamBasicRiki/Riki/wiki/web/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock title %}

{% block content %}
    <form class="form form-inline" method="POST">
        {{ form.hidden_tag() }}
        {{ form.name(placeholder='Username') }}
        {{ form.password(placeholder='Password') }}
        <input type="submit" class="btn btn-primary" value="Login">
    </form>

    <div style="text-align: center; margin-top: 20px;">
        <form class="form form-inline" method="GET" action="{{ url_for('wiki.user_create') }}">
            <button type="submit" class="btn btn-primary">Create an account</button>
        </form>
    </div>
{% endblock content %}

TeamBasicRiki/Riki/wiki/web/templates/move.html
{% extends "base.html" %}

{% block title %}Move a page{% endblock title %}
{% block content %}
<form method="POST" class="form-inline">
    {{ form.hidden_tag() }}
    {{ input(form.url, placeholder="New URL of the page", autocomplete="off") }}
    <input type="submit" class="btn btn-success" value="Create">
</form>
{% endblock content %}

{% block sidebar %}
<p class="alert alert-success">Be careful, the old url will be invalid immediately!</p>
{% endblock sidebar %}

TeamBasicRiki/Riki/wiki/web/templates/page.html
{% extends "base.html" %}

{% block title %}
    {{ page.title }}
{% endblock title %}

{% block content %}
    <div id="confirmDelete" class="modal hide fade" aria-hidden="true">
        <div class="modal-header">
            <h3>Are you sure?</h3>
        </div>
        <div class="modal-body">
            <p>Are you sure you want to delete {{ page.title }}? This cannot be undone.</p>
        </div>
        <div class="modal-footer">
            <a href="#" class="btn" data-dismiss="modal" aria-hidden="true">No</a>
            <a href="{{ url_for('wiki.delete', url=page.url) }}" class="btn btn-danger">Yes, delete.</a>
        </div>
    </div>

    <div id="download" class="modal hide fade" aria-hidden="true">
        <div class="modal-header">
            <h3>Download Page</h3>
        </div>
        <div class="modal-body">
            <p>To download the page, please select the file type you want to download the page in using the dropdown box below and press convert</p>
            <div class="form-group">
                <label for="fileType">Select File Type:</label>
                <select class="form-control" id="fileType">
                    <option>select</option>
                    <option value="md">MD</option>
                    <option value="pdf">PDF</option>
                    <option value="txt">TXT</option>
                    <option value="html">HTML</option>
                    <option value="docx">DOCX</option>
                </select>
            </div>
            <button id="convertBtn" class="btn btn-primary">Convert</button>

            <div id="conversionResult"></div>
        </div>

        <div class="modal-footer" id="modalFooter">
            <a href="#" class="btn" data-dismiss="modal" aria-hidden="true">Cancel</a>
            <button id="downloadBtn" class="btn btn-primary">Download</button>
        </div>
    </div>

    {{ page }}

    {% block postscripts %}
        <script src="{{ url_for('static', filename='conversion_script.js') }}"></script>
    {% endblock postscripts %}
{% endblock content %}

{% block sidebar %}
    {% if page.tags %}
        <h3>Tags</h3>
        <ul>
            {% for tag in page.tags.split(',') %}
                <li><a href="{{ url_for('wiki.tag', name=tag.strip()) }}">{{ tag|trim }}</a></li>
            {% endfor %}
        </ul>
    {% endif %}
    <h3>Actions</h3>
    <ul class="nav nav-tabs nav-stacked">
        <li><a href="{{ url_for('wiki.edit', url=page.url) }}">Edit</a></li>
        <li><a href="{{ url_for('wiki.move', url=page.url) }}">Move</a></li>
        <li><a href="#download" data-toggle="modal">Download Page</a></li>
        <li><a href="#confirmDelete" data-toggle="modal" class="text-error">Delete</a></li>
    </ul>
{% endblock sidebar %}

TeamBasicRiki/Riki/wiki/web/templates/register.html
{% extends "base.html" %}

{% block title %}Create Your Account{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-md-6">
            <form class="form" method="POST">
                {{ form.hidden_tag() }}

                <div class="form-group">
                    {{ form.username(placeholder='Enter your username', class='form-control') }}
                </div>

                <div class="form-group">
                    {{ form.password(placeholder='Enter Your Password', class='form-control') }}
                </div>

                <div class="form-group">
                    {{ form.confirmPassword(placeholder='Confirm Your Password', class='form-control') }}
                </div>

                <div class="form-group">
                    {{ form.email(placeholder='Enter Your Email Address', class='form-control') }}
                </div>

                <button type="submit" class="btn btn-primary">Sign up</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

TeamBasicRiki/Riki/wiki/web/templates/search.html
{% extends "base.html" %}

{% block title %}
{% if search %}
	Results for "{{ search }}"
{% else %}
	Search
{% endif %}
{% endblock title %}

{% block content %}
<div class="row">
	<div class="span8 offset1">
		<form class="form-inline well" method="POST">
			{{ form.hidden_tag() }}
			{{ form.term(placeholder='Search for.. (regex accepted)', autocomplete="off") }}
            {{ form.ignore_case() }} Ignore Case
			<input type="submit" class="btn btn-success pull-right" value="Search!">
		</form>
	</div>
</div>

{% if search %}
	{% if results %}
		<ul>
			{% for result in results %}
				<li><a href="{{ url_for('wiki.display', url=result.url) }}">{{ result.title }}</a></li>
			{% endfor %}
		</ul>
	{% else %}
		<p>No results for your search.</p>
	{% endif %}
{% endif %}
{% endblock content %}

TeamBasicRiki/Riki/wiki/web/templates/tags.html
{% extends "base.html" %}

{% block title %}Index by Tags{% endblock title %}

{% block content %}
{% if tags %}
	<table class="table">
		<thead>
			<tr>
				<th>Tag</th>
				<th>Number of Articles</th>
			</tr>
		</thead>
		<tbody>
			{% for tag, pages in tags|dictsort %}
				<tr>
					<td><a href="{{ url_for('wiki.tag', name=tag) }}">{{ tag }}</a></td>
					<td>{{ pages|length }}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>There are no tags in use so far.</p>
{% endif %}
{% endblock content %}